# Generated by Django 5.2.4 on 2025-11-08 10:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ReelBlog', '0002_post_images'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='image',
        ),
    ]
