# Generated by Django 5.2.4 on 2025-11-08 10:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ReelBlog', '0003_remove_post_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='images',
            new_name='image',
        ),
    ]
